---
- hosts: localhost
  connection: local
  tasks:
      - name: set fact for time variable to use as part of the Name tag
        set_fact:
            fact_time: "{{ lookup('pipe', 'date \"+%Y%m%d%H%M%S\"') }}"
  tags: [asg, terminate, instance, instance-ami]

- hosts: "tag_Name_ami_build"
  gather_facts: false
  tasks:
    - name:  Find existing instance(s) and add to old-ami-build group
      group_by:
        key: old_ami_build
  tags: [terminate]

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
      - instance-template
  tags: [instance, instance-ami]

- hosts: ami_build
  user: "{{ login_user_debian }}"
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  roles:
      - install-nginx
  tags: [nginx]

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
      - create-ami
      - create-lc
      - create-elb
      - create-asg
  tags: [ami, instance-ami]

- hosts: old_ami_build
  connection: local
  gather_facts: no
  roles:
    - terminate-instances
  tags: [terminate]
