---
# instance-template/tasks/main.yml
- name: launch ec2 instances
  ec2:
    region: "{{ region }}"
    zone: "{{ zone }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
        Name: "{{ instance_group }}"
        role: template
    image: "{{ ami_debian }}"
    group: "{{ security_groups }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: yes
    count: 1
  register: ec2_info

- name: Add new instance to host group
  add_host: name={{ item.public_ip }} groups={{ instance_group }}
  #add_host: name={{ item.public_dns_name }} groups={{ instance_group }} ec2_id={{ item.id }}
  with_items: ec2_info.instances

- name: Wait for SSH to come up indicating instance is booted
  wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
  with_items: ec2_info.instances
